### ISSUE TITLE
方法重写 编译失败

### ISSUE THREAD

**Issue by dongbeicxy** [TonnyL/Charles#11]
朋友,你好
override fun onSaveInstanceState(outState: Bundle?) {
        super.onSaveInstanceState(outState)
        outState?.let {
            mSelectedCollection.onSaveInstanceState(it)
        }
    }

鼠标放在outState变量那   提示 
Type mismatch.
Required:
Context
Found:
Context?

**Comment by TonnyL** [comment]
@xingzhibiao 

确认升级到了最新的 support library 了么？
