### ISSUE TITLE
多媒体库所有文件夹同步问题

### ISSUE THREAD

**Issue by Yis92** [TonnyL/Charles#7]
请问针对其他app刚刚下载的文件如何做到同步，

如何同步根目录下的所有文件 ， 到多媒体库中

**Comment by Yis92** [comment]
貌似这个只能同步某个具体的文件，而且还只支持4.4以下版本，我需要同步所有的文件，您的项目中【文件里】也有这个同步的问题，可否您修改下这个问题，提交下，我学习下

**Comment by TonnyL** [comment]
你可以试试 https://www.jianshu.com/p/45f1b6e9b1a5 这篇文章提供的方法。很抱歉，我的这个项目并没有考虑到需要手动到去同步所有到文件，只考虑了MediaStore中现有的文件。

**Comment by Yis92** [comment]
谢谢

**Comment by TonnyL** [comment]
不客气，有任何问题欢迎随时交流😉
