### ISSUE TITLE
文件不支持选择doc xls ppt pdf?

### ISSUE THREAD

**Issue by 1391884664** [TonnyL/Charles#9]
文件不支持选择doc xls ppt pdf?

**Comment by TonnyL** [comment]
还不支持，有需求的话可以自己改一下，我最近也没啥时间改😂

**Comment by 1391884664** [comment]
可以告诉我在哪个具体的地方修改吗？

**Comment by TonnyL** [comment]
https://github.com/TonnyL/Charles/blob/master/charles/src/main/java/io/github/tonnyl/charles/internal/loader/MediaItemLoader.kt#L101

**Comment by 1391884664** [comment]
看到你写了获取 pdf doc xls了  ，为什么没生效呢？

**Comment by TonnyL** [comment]
不太清楚，估计是 bug 吧，很久没看代码我也不太确定

**Comment by 1391884664** [comment]
![image](https://user-images.githubusercontent.com/16079507/50267189-58394d80-0461-11e9-869f-440f95cb88f1.png)
这样就可以了，谢谢大神！

**Comment by TonnyL** [comment]
👍

**Comment by TonnyL** [comment]
如果没有其他问题，我先关闭这个 issue 了，有其他问题请 reopen 或者直接开一个新 issue。😉
